Repository AY2122S2-CS2113-F10-4/tp, pull requests merged in 2022-04, with the labels that each got.

#94 Minor typo in UserGuide - Expense Tracker List
  docs/UserGuide.md
Labels: type.Bug, priority.Low

#130 Expense Tracker - Fix bugs from PED
  docs/UserGuide.md
  src/main/java/seedu/allonus/expense/ExpenseParser.java
  src/main/java/seedu/allonus/expense/ExpenseTracker.java
  src/main/java/seedu/allonus/expense/exceptions/ExpenseExtraFieldException.java
  src/main/java/seedu/allonus/expense/exceptions/ExpenseSurroundSlashSpaceException.java
  src/test/java/seedu/allonus/expense/ExpenseParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, priority.Medium

#145 Expense Tracker Documentation Enhancements
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/yithien.md
  src/main/java/seedu/allonus/expense/ExpenseParser.java
  src/main/java/seedu/allonus/expense/ExpenseTracker.java
  src/test/java/seedu/allonus/expense/ExpenseParserTest.java
Labels: type.Enhancement, priority.Medium

#150 Modules add tests and documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/GradManagerClassDiagram.puml
  docs/diagrams/ModuleClassDiagram.puml
  docs/diagrams/ModulesTaskListClassDiagram.puml
  docs/diagrams/ModulesTaskListSequenceDiagram.puml
  docs/diagrams/StudyManagerSequenceDiagramAdd.puml
  docs/images/GradManagerClassDiagram.png
  docs/images/ModuleClassDiagram.png
  docs/images/ModulesTaskListClassDiagram.png
  docs/images/ModulesTaskListSequenceDiagram.png
  docs/images/StudyManagerSequenceDiagram.png
  src/main/java/seedu/allonus/modules/ModuleCalendarReader.java
  src/main/java/seedu/allonus/modules/ModuleParser.java
  src/main/java/seedu/allonus/modules/StudyManager.java
  src/test/java/seedu/allonus/modules/ModuleCalendarReaderTest.java
  src/test/java/seedu/allonus/modules/ModuleParserTest.java
  src/test/java/seedu/allonus/modules/ModuleTest.java
  src/test/java/seedu/allonus/modules/StudyManagerTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High
