Repository AY2122S2-CS2113-F10-4/tp, pull requests merged in 2022-03, with the labels that each got.

#13 Implement skeleton for contacts manager
  docs/AboutUs.md
  docs/team/wli-linda.md
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/contacts/Contact.java
  src/main/java/seedu/duke/contacts/ContactsManager.java
  src/main/java/seedu/duke/ui/TextUi.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, priority.High

#42 Study manager JavaDoc and UserGuide documentation
  docs/UserGuide.md
  src/main/java/seedu/allonus/modules/Module.java
  src/main/java/seedu/allonus/modules/StudyManager.java
  src/main/java/seedu/allonus/modules/exceptions/ModuleCategoryException.java
  src/main/java/seedu/allonus/modules/exceptions/ModuleCodeException.java
  src/main/java/seedu/allonus/modules/exceptions/ModuleDayException.java
  src/main/java/seedu/allonus/modules/exceptions/ModuleTimeException.java
  src/test/java/seedu/allonus/modules/ModuleTest.java
  src/test/java/seedu/allonus/modules/StudyManagerTest.java
Labels: type.Chore

#45 Change logger log levels and build jar file
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/seedu/allonus/AllOnUs.java
  src/main/java/seedu/allonus/expense/ExpenseTracker.java
  src/main/java/seedu/allonus/modules/StudyManager.java
Labels: type.Chore

#64 Add basic find and edit features for Module Manager
  docs/DeveloperGuide.md
  docs/images/StudyManagerClass.png
  src/main/java/seedu/allonus/modules/Module.java
  src/main/java/seedu/allonus/modules/StudyManager.java
  src/main/java/seedu/allonus/modules/exceptions/ModuleCategoryException.java
  src/main/java/seedu/allonus/modules/exceptions/ModuleCodeException.java
  src/main/java/seedu/allonus/modules/exceptions/ModuleDayException.java
  src/main/java/seedu/allonus/modules/exceptions/ModuleTimeException.java
Labels: priority.Medium

#65 Add basic functionality for Edit feature of Expense Tracker
  docs/UserGuide.md
  src/main/java/seedu/allonus/expense/Expense.java
  src/main/java/seedu/allonus/expense/ExpenseParser.java
  src/main/java/seedu/allonus/expense/ExpenseTracker.java
  src/test/java/seedu/allonus/expense/ExpenseParserTest.java
  src/test/java/seedu/allonus/expense/ExpenseTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, priority.High

#72 Minor bug fix to Expense Tracker Junit Test
  src/test/java/seedu/allonus/expense/ExpenseParserTest.java
  src/test/java/seedu/allonus/expense/ExpenseTest.java
Labels: type.Bug, priority.Low

#69 Add Draft Developer Guide for Expense Tracker
  docs/DeveloperGuide.md
  docs/diagrams/BudgetingReminder0.puml
  docs/diagrams/BudgetingReminder1.puml
  docs/diagrams/BudgetingReminder2.puml
  docs/diagrams/BudgetingReminderSequenceDiagram.puml
  docs/diagrams/ExpenseClassDiagram.puml
  docs/diagrams/Style.puml
  docs/images/BudgetingReminder0.png
  docs/images/BudgetingReminder1.png
  docs/images/BudgetingReminder2.png
  docs/images/BudgetingReminderSequenceDiagram.png
  docs/images/ExpenseClassDiagram.png
Labels: type.Chore, priority.Medium

#75 Add constraints on Date and Amount fields; add additional custom exceptions and Junit tests
  build.gradle
  src/main/java/seedu/allonus/AllOnUs.java
  src/main/java/seedu/allonus/expense/Expense.java
  src/main/java/seedu/allonus/expense/ExpenseException.java
  src/main/java/seedu/allonus/expense/ExpenseParser.java
  src/main/java/seedu/allonus/expense/ExpenseTracker.java
  src/main/java/seedu/allonus/expense/exceptions/ExpenseAmountException.java
  src/main/java/seedu/allonus/expense/exceptions/ExpenseEmptyFieldException.java
  src/main/java/seedu/allonus/expense/exceptions/ExpenseMissingFieldException.java
  src/test/java/seedu/allonus/expense/ExpenseAmountExceptionTest.java
  src/test/java/seedu/allonus/expense/ExpenseEmptyFieldExceptionTest.java
  src/test/java/seedu/allonus/expense/ExpenseMissingFieldExceptionTest.java
  src/test/java/seedu/allonus/expense/ExpenseParserTest.java
  src/test/java/seedu/allonus/expense/ExpenseTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement, priority.Medium

#76 Add enhancements to find, edit features and add parse ics feature
  build.gradle
  docs/UserGuide.md
  ical4j/ical4j.jar
  nusmods_calendar.ics
  src/main/java/seedu/allonus/modules/ModuleCalendarReader.java
  src/main/java/seedu/allonus/modules/StudyManager.java
  src/main/java/seedu/allonus/modules/exceptions/InvalidFindInputException.java
Labels: type.Epic, priority.Medium

#78 Improve Contacts Manager's related documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ContactClassDiagram.puml
  docs/diagrams/ContactSetFieldsSequence.puml
  docs/diagrams/ContactSetFieldsSequenceSubdiagram.puml
  docs/diagrams/Style.puml
  docs/images/ContactClassDiagram.png
  docs/images/ContactSetFieldsSequence.png
  docs/images/ContactSetFieldsSequenceSubdiagram.png
  src/main/java/seedu/allonus/contacts/ContactParser.java
  src/main/java/seedu/allonus/contacts/ContactsManager.java
  src/main/java/seedu/allonus/contacts/InvalidContactField.java
  src/main/java/seedu/allonus/contacts/entry/Contact.java
  src/main/java/seedu/allonus/contacts/entry/Description.java
  src/main/java/seedu/allonus/contacts/entry/Email.java
  src/main/java/seedu/allonus/contacts/entry/Faculty.java
  src/main/java/seedu/allonus/contacts/entry/Field.java
  src/main/java/seedu/allonus/contacts/entry/Name.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Chore, priority.Medium

#81 Add minor changes to UserGuide
  docs/UserGuide.md
  src/main/java/seedu/allonus/expense/ExpenseParser.java
  src/main/java/seedu/allonus/expense/ExpenseTracker.java
  src/test/java/seedu/allonus/expense/ExpenseParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Chore, priority.Low
